# Generated by Django 6.0.1 on 2026-02-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestellung',
            name='art',
            field=models.CharField(choices=[('LOKAL', 'Vor Ort essen'), ('TAKEAWAY', 'Takeaway / Bestellen')], default='TAKEAWAY', max_length=10),
        ),
    ]
