# Generated by Django 6.0.2 on 2026-02-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_app', '0003_gericht_kategorie_gericht_reihenfolge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestellung',
            name='art',
            field=models.CharField(choices=[('LOKAL', 'Im Restaurant essen'), ('TAKEAWAY', 'Take-Away'), ('DELIVERY', 'Bestellen')], default='TAKEAWAY', max_length=20),
        ),
    ]
