# Generated by Django 6.0.2 on 2026-02-04 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_app', '0004_alter_bestellung_art'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='mindestbestellwert',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Min. Bestellwert'),
        ),
        migrations.CreateModel(
            name='Stimme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(auto_now_add=True)),
                ('benutzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stimmen', to='lunch_app.restaurant')),
            ],
            options={
                'unique_together': {('benutzer', 'datum')},
            },
        ),
    ]
