# Generated by Django 6.0.2 on 2026-02-05 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_app', '0005_restaurant_mindestbestellwert_stimme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('benutzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoriten', to=settings.AUTH_USER_MODEL)),
                ('gericht', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorisiert_von', to='lunch_app.gericht')),
            ],
            options={
                'unique_together': {('benutzer', 'gericht')},
            },
        ),
    ]
