# Generated by Django 6.0.2 on 2026-02-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_app', '0006_favorit'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestellung',
            name='notiz',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
