# Generated by Django 6.0.2 on 2026-02-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_app', '0007_bestellung_notiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='website',
            field=models.URLField(blank=True, verbose_name='Webseite'),
        ),
    ]
