# Generated by Django 6.0.2 on 2026-02-05 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_app', '0008_restaurant_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='website',
        ),
    ]
