# Generated by Django 6.0.2 on 2026-02-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_app', '0009_remove_restaurant_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='website',
            field=models.URLField(blank=True, verbose_name='Webseite/Link'),
        ),
    ]
