# Generated by Django 6.0.2 on 2026-02-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_app', '0010_restaurant_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='biete_delivery',
            field=models.BooleanField(default=False, verbose_name='Bietet Lieferung'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='biete_lokal',
            field=models.BooleanField(default=True, verbose_name='Bietet Essen vor Ort'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='biete_takeaway',
            field=models.BooleanField(default=True, verbose_name='Bietet Take-Away'),
        ),
    ]
