# Generated by Django 6.0.2 on 2026-02-06 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_app', '0011_restaurant_biete_delivery_restaurant_biete_lokal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestellung',
            name='optionen_text',
            field=models.TextField(blank=True, null=True, verbose_name='Gewählte Optionen'),
        ),
        migrations.CreateModel(
            name='OptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pflicht', models.BooleanField(default=True, verbose_name='Auswahl ist Pflicht')),
                ('reihenfolge', models.IntegerField(default=0)),
                ('gericht', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_groups', to='lunch_app.gericht')),
            ],
            options={
                'ordering': ['reihenfolge'],
            },
        ),
        migrations.CreateModel(
            name='OptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('aufpreis', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('reihenfolge', models.IntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lunch_app.optiongroup')),
            ],
            options={
                'ordering': ['reihenfolge'],
            },
        ),
    ]
