# Generated by Django 6.0.2 on 2026-02-06 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_app', '0012_bestellung_optionen_text_optiongroup_optionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionitem',
            name='gericht_verweis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lunch_app.gericht', verbose_name='Existierendes Gericht verknüpfen'),
        ),
        migrations.AlterField(
            model_name='optionitem',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name (oder leer lassen wenn Gericht gewählt)'),
        ),
    ]
