# Generated by Django 6.0.2 on 2026-02-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_app', '0013_optionitem_gericht_verweis_alter_optionitem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='optiongroup',
            name='typ',
            field=models.CharField(choices=[('RADIO', 'Einzelwahl (Nur eines wählbar)'), ('CHECKBOX', 'Mehrfachwahl (Ankreuzen)'), ('NUMBER', 'Mengenwahl (Zähler 0-15)')], default='RADIO', max_length=20),
        ),
        migrations.AlterField(
            model_name='optiongroup',
            name='pflicht',
            field=models.BooleanField(default=False, verbose_name='Auswahl ist Pflicht'),
        ),
    ]
