# Generated by Django 6.0.2 on 2026-02-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_app', '0014_optiongroup_typ_alter_optiongroup_pflicht'),
    ]

    operations = [
        migrations.AddField(
            model_name='stimme',
            name='art',
            field=models.CharField(choices=[('LOKAL', 'Im Restaurant essen'), ('TAKEAWAY', 'Take-Away'), ('DELIVERY', 'Bestellen')], default='LOKAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='optiongroup',
            name='pflicht',
            field=models.BooleanField(default=True, verbose_name='Auswahl ist Pflicht'),
        ),
    ]
