# Generated by Django 6.0.2 on 2026-02-10 07:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_app', '0015_stimme_art_alter_optiongroup_pflicht'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='optiongroup',
            name='pflicht',
            field=models.BooleanField(default=False, verbose_name='Auswahl ist Pflicht'),
        ),
        migrations.CreateModel(
            name='TagesVerantwortlicher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(default=django.utils.timezone.now)),
                ('bestellzeit', models.CharField(blank=True, help_text='z.B. 12:00', max_length=20, null=True)),
                ('nutzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunch_app.restaurant')),
            ],
            options={
                'unique_together': {('restaurant', 'datum')},
            },
        ),
    ]
