# Generated by Django 6.0.2 on 2026-02-10 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_app', '0017_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schulden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=6)),
                ('datum', models.DateField(auto_now_add=True)),
                ('erledigt', models.BooleanField(default=False)),
                ('glaeubiger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guthaben_eintraege', to=settings.AUTH_USER_MODEL)),
                ('schuldner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schulden_eintraege', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
