# Generated by Django 6.0.2 on 2026-02-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_app', '0018_schulden'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='letztes_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='scraper_modul',
            field=models.CharField(blank=True, help_text='Name der Funktion in scrapers.py (z.B. scrape_adler)', max_length=100, null=True),
        ),
    ]
