# Generated by Django 6.0.2 on 2026-02-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_app', '0019_restaurant_letztes_update_restaurant_scraper_modul'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagesverantwortlicher',
            name='bestellung_bestaetigt',
            field=models.BooleanField(default=False),
        ),
    ]
