# Generated by Django 6.0.2 on 2026-02-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_app', '0020_tagesverantwortlicher_bestellung_bestaetigt'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notify_daily',
            field=models.BooleanField(default=True, verbose_name='Tägliche Erinnerung (10:00 Uhr)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_debt',
            field=models.BooleanField(default=True, verbose_name='Täglicher Schulden-Report'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_order_confirm',
            field=models.BooleanField(default=True, verbose_name='Bestätigung bei Bestellung'),
        ),
    ]
