# Generated by Django 6.0.2 on 2026-02-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_app', '0021_userprofile_notify_daily_userprofile_notify_debt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagesverantwortlicher',
            name='art',
            field=models.CharField(choices=[('LOKAL', 'Lokal'), ('TAKEAWAY', 'Takeaway'), ('DELIVERY', 'Lieferung')], default='DELIVERY', max_length=20),
        ),
    ]
