# Generated by Django 6.0.2 on 2026-02-10 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_app', '0022_tagesverantwortlicher_art'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tagesverantwortlicher',
            unique_together={('restaurant', 'datum', 'art')},
        ),
    ]
