# Generated by Django 6.0.2 on 2026-02-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_app', '0023_alter_tagesverantwortlicher_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='show_phone',
            field=models.BooleanField(default=False, verbose_name='Handynummer anzeigen'),
        ),
    ]
