# Generated by Django 6.0.2 on 2026-02-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_app', '0025_bewertung'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestellung',
            name='bewertungs_mail_gesendet',
            field=models.BooleanField(default=False),
        ),
    ]
