# Generated by Django 6.0.2 on 2026-02-11 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_app', '0026_bestellung_bewertungs_mail_gesendet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bestellung',
            name='bewertungs_mail_gesendet',
        ),
        migrations.DeleteModel(
            name='Bewertung',
        ),
    ]
