# Generated by Django 6.0.2 on 2026-02-11 14:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_app', '0027_remove_bestellung_bewertungs_mail_gesendet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schulden',
            name='datum',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
