# Generated by Django 6.0.2 on 2026-02-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_app', '0028_alter_schulden_datum'),
    ]

    operations = [
        migrations.AddField(
            model_name='schulden',
            name='zahlungsart',
            field=models.CharField(choices=[('TWINT_REQ', 'TWINT Anforderung'), ('TWINT_SEND', 'TWINT gesendet'), ('SONST', 'Sonstiges')], default='SONST', max_length=20),
        ),
    ]
