# Generated by Django 6.0.2 on 2026-02-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_app', '0029_schulden_zahlungsart'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagesverantwortlicher',
            name='zahlungsart',
            field=models.CharField(default='SONST', max_length=20),
        ),
    ]
