# Generated by Django 6.0.2 on 2026-02-12 09:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_app', '0030_tagesverantwortlicher_zahlungsart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tagesverantwortlicher',
            name='fahrer',
            field=models.ManyToManyField(blank=True, related_name='fahrten', to=settings.AUTH_USER_MODEL),
        ),
    ]
