# Generated by Django 6.0.2 on 2026-03-09 10:11

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_app', '0033_standort_alter_tagesverantwortlicher_nutzer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemEinstellungen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bestellschluss', models.TimeField(default=datetime.time(11, 0), verbose_name='Bestellschluss (Uhrzeit)')),
            ],
            options={
                'verbose_name': 'System-Einstellung',
                'verbose_name_plural': 'System-Einstellungen',
            },
        ),
        migrations.AlterModelOptions(
            name='bestellung',
            options={'verbose_name': 'Bestellung', 'verbose_name_plural': 'Bestellungen'},
        ),
        migrations.AlterModelOptions(
            name='favorit',
            options={'verbose_name': 'Favorit', 'verbose_name_plural': 'Favoriten'},
        ),
        migrations.AlterModelOptions(
            name='gericht',
            options={'verbose_name': 'Gericht', 'verbose_name_plural': 'Gerichte'},
        ),
        migrations.AlterModelOptions(
            name='optiongroup',
            options={'ordering': ['reihenfolge'], 'verbose_name': 'Option Group', 'verbose_name_plural': 'Option Groups'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name': 'Restaurant', 'verbose_name_plural': 'Restaurants'},
        ),
        migrations.AlterModelOptions(
            name='schulden',
            options={'verbose_name': 'Schuld', 'verbose_name_plural': 'Schulden'},
        ),
        migrations.AlterModelOptions(
            name='standort',
            options={'verbose_name': 'Standort', 'verbose_name_plural': 'Standorte'},
        ),
        migrations.AlterModelOptions(
            name='stimme',
            options={'verbose_name': 'Stimme', 'verbose_name_plural': 'Stimmen'},
        ),
        migrations.AddField(
            model_name='bestellung',
            name='lokal_anmeldung',
            field=models.BooleanField(default=False, verbose_name='Nur Anmeldung (Lokal)'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='liefergebuehren',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Liefergebühren (CHF)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='abwesend_bis',
            field=models.DateField(blank=True, null=True, verbose_name='Abwesend/Urlaub bis (inklusive)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='abwesend_von',
            field=models.DateField(blank=True, null=True, verbose_name='Abwesend/Urlaub von'),
        ),
        migrations.AlterField(
            model_name='bestellung',
            name='gericht',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lunch_app.gericht'),
        ),
        migrations.AlterField(
            model_name='tagesverantwortlicher',
            name='nutzer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tagesverantwortlicher',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lunch_app.restaurant'),
        ),
        migrations.CreateModel(
            name='Oeffnungszeit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wochentag', models.IntegerField(choices=[(0, 'Montag'), (1, 'Dienstag'), (2, 'Mittwoch'), (3, 'Donnerstag'), (4, 'Freitag'), (5, 'Samstag'), (6, 'Sonntag')])),
                ('oeffnet_um', models.TimeField(blank=True, null=True)),
                ('schliesst_um', models.TimeField(blank=True, null=True)),
                ('geschlossen', models.BooleanField(default=False, verbose_name='Heute geschlossen')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zeiten', to='lunch_app.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='SpezialSchliessung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('ist_geschlossen', models.BooleanField(default=True, verbose_name='An diesem Tag geschlossen')),
                ('notiz', models.CharField(blank=True, help_text='z.B. Auffahrt', max_length=100)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ausnahmen', to='lunch_app.restaurant')),
            ],
        ),
    ]
